name: 'Terraform Plan Apply'

on:
  push:
    branches: [ "main" ]

jobs:
  terraform-plan:
    name: 'Terraform-Plan'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform init

    - name: Terraform Format
      run: terraform fmt

    - name: Terraform Validate
      run: terraform validate